create table client
(
    id   bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table address
(
    address_owner_id bigint not null unique references client (id) on delete cascade,
    street           varchar(100) not null
);

create table phone
(
    id             bigint generated by default as identity primary key,
    phone_owner_id bigint not null references client (id) on delete cascade,
    number         varchar(20) not null
);

create index idx_address_owner_id on address (address_owner_id);
create index idx_phone_owner_id on phone (phone_owner_id);
